### ISSUE TITLE
Feature Request: Clickable IDs that auto-copy id to clipboard

### ISSUE THREAD

**Issue by artokun** [DotEfekts/TradeCommander#1]
It would be nice to get a one-click copy of the IDs to be used on CLI options easily

![Screen Shot 2021-03-08 at 10 03 35 PM](https://user-images.githubusercontent.com/7666455/110426244-9a5b0380-805a-11eb-9204-1c772fe59f63.png)

**Comment by DotEfekts** [comment]
Ship Id in commands refers to the local Id listed on the far left. You can use the server Id as it's the default ship name but only if you haven't used the rename command. I can still add a click to copy the name to the clipboard if you think it would be useful though?

**Comment by artokun** [comment]
Ah rename is so cool!

**Comment by artokun** [comment]
I would only recommend it so that every time you make a new ship, renaming it would be easy

**Comment by DotEfekts** [comment]
Given that ships are now given readable names by default, and app ship id's short, I'm going to close this one as I don't see any real need for it, especially once auto-complete is finished.
